exports.recipes = [
    {
        name: 'Instant Pot Plov (Rice Pilaf)',
        description: 'Making beef plov in an instant pot is so quick and easy and using brown rice is genius. This Instant Pot Rice recipe is a healthier, juicier and flavor packed version of beef plov.',
        ingredients: [
            { qty: '2 1/2 cups', name: 'short grain brown rice', prep: 'rinsed and drained' },
            { qty: '1 lb', name: 'beef chuck or beef stew meat', prep: 'cut into 3/4″ pieces' },
            { qty: '4 Tbsp', name: 'olive oil' },
            { qty: '4 Tbsp', name: 'butter' },
            { qty: '1', name: 'large onion', prep: 'diced' },
            { qty: '3', name: 'large carrots', prep: 'thickly julienned' },
            { qty: '3 cups', name: 'very warm water' },
            { qty: '1 Tbsp', name: 'salt' },
            { qty: '1/2 tsp', name: 'black pepper' },
            { qty: '1/2 tsp', name: 'ground cumin' },
            { qty: '1/2 tsp', name: 'ground paprika' },
            { qty: '1/2 tsp', name: 'ground coriander' },
            { qty: '1', name: 'whole head garlic', prep: 'unpeeled, cut in half crosswise' },
            { qty: '1 Tbsp', name: 'freshly chopped parsley to garnish – optional' },
        ],
        instructions: [
            `Rinse and drain rice and set aside. Set Instant pot to sauté on high heat (push sauté twice to switch to high heat) and add 4 Tbsp olive oil. Once oil is hot (but not smoking), add beef in a single layer and sauté until lightly browned (5 min), stirring occasionally.`,
            `Add 4 Tbsp butter and chopped onion and stir 3 minutes until softened.`,
            `Add julienned carrots along with all seasonings (1 Tbsp salt, 1/2 tsp pepper, 1/2 tsp cumin, 1/2 tsp paprika, 1/2 tsp coriander) and sauté 5 minutes until softened, stirring occasionally.`,
            `pread rice evenly over the top (do not stir). Push garlic halves cut-side-down, halfway into the rice. Pour very warm (or hot) water directly over the garlic cloves so you don't disturb the rice. Use the back of a wooden spoon to poke 5-7 holes through the rice to the bottom of the pot (this helps disburse flavor).`,
            `Cover and cook on high pressure 30 min (I used the "Multigrain" setting). Let instant pot rest and naturally depressurize 10 min before switching to the venting position to release steam. Make sure the steam is fully released and the pressure valve has floated down before opening the pot.`,
            `Remove garlic and set aside. Stir rice well to combine ingredients. We squeeze the garlic cloves back into the pot because they are melt-in-your mouth delicious.`
        ],
        skillLevel: 'Easy',
        timePrep: 20,
        timeWait: null,
        timeCook: 30,
        servings: 8,
        categories: [
            'dinner',
            'main',
            'side',
            'lunch',
            'beef',
            'lamb',
            'meat',
            'entree',
            'rice',
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/6j40kRP.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Borscht',
        description: '',
        ingredients: [
            { qty: '1 lb', name: 'Beef: sirloin, stew meat', prep: 'cut into 1 inch cubes'},
            { qty: '14 cups', name: 'water'},
            { qty: '1 Tbsp', name: 'salt + more to taste'},
            { qty: '2', name: 'large or 3 medium beets', prep: 'washed, peeled, and grated'},
            { qty: '4 Tbsp', name: 'olive oil'},
            { qty: '1 Tbsp', name: 'vinegar'},
            { qty: '1 Tbsp', name: 'sugar'},
            { qty: '2 Tbsp', name: 'tomato paste'},
            { qty: '1 Tbsp', name: 'butter'},
            { qty: '1', name: 'medium onion', prep: 'finely diced'},
            { qty: '2', name: 'carrots', prep: 'grated'},
            { qty: '2', name: 'large or 3 medium potatoes', prep: 'peeled and sliced into bite-sized pieces'},
            { qty: '1/2 head', name: 'small cabbage', prep: 'julienned'},
            { qty: '2', name: 'tomatoes', prep: 'peeled and diced (**see note)'},
            { qty: '2', name: 'bay leaves'},
            { qty: '1/4 tsp', name: 'freshly ground pepper'},
            { qty: '1/4 cup', name: 'fresh parsley', prep: 'chopped'},
            { qty: '2 cloves', name: 'garlic', prep: 'pressed'},
        ],
        instructions: [
            `Wash meat in cold water, cut into 1" pieces and and place in a large soup pot with 14 cups cold water and 1 Tbsp salt. Bring it to a boil and remove the foam crud as soon as it boils (if you wait, it will be hard to get rid of the crud as it integrates into the broth and you'd have to strain it later). Reduce heat, partially cover and simmer 45 minutes - 1 hr, periodically skimming off any crud that rises to the top.`,
            `Grate beets on the large grater holes (a food processor works amazingly well). Place them in a large heavy-bottom skillet with 4 Tbsp olive oil and 1 Tbsp vinegar and saute for 5 minutes, then reduce heat to med/low and add 1 Tbsp sugar and 2 Tbsp tomato sauce Mix thoroughly and saute until starting to soften, stirring occasionally (about 10 min). Remove from pan and set aside.`,
            `In the same skillet (no need to wash it), Saute onion in 1 Tbsp butter for 2 min. Add grated carrot and sautee another 5 min or until softened, adding more oil if it seems too dry.`,
            `Once the meat has been cooking at least 45 min, place sliced potatoes into`,
            `the soup pot and cook 10 min, then add cabbage, sauteed beets, onion & carrot, and chopped tomatoes. Cook another 10 minutes or until potatoes can be easily pierced with a fork.`,
            `Add 2 bay leaves, 1/4 tsp pepper, and more salt to taste (I added another 1/2 tsp salt).`,
            `Chop parsley and pressed garlic then stir them into the soup pot, immediately cover and remove from heat. Let the pot rest covered for 20 minutes for the flavors to meld.`,
        ],
        skillLevel: 'Medium',
        timePrep: 30,
        timeWait: null,
        timeCook: 90,
        servings: 8,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/qrq8Bmv.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Hungarian Goulash',
        description: '',
        ingredients: [
            {qty: '4 tbsp', name: 'olive oil'},
            {qty: '2 1/2 lbs', name: 'lean stewing beef', prep: 'cut into 1 inch pieces'},
            {qty: '1 tsp', name: 'salt or to taste'},
            {qty: '1 tsp', name: 'pepper or to taste'},
            {qty: '2', name: 'large onions', prep: 'roughly chopped'},
            {qty: '5 cloves', name: 'garlic', prep: 'minced'},
            {qty: '3 tbsp', name: 'sweet paprika'},
            {qty: '1 tsp', name: 'caraway seeds', prep: 'ground'},
            {qty: '1 tsp', name: 'dried oregano'},
            {qty: '3', name: 'bay leaves'},
            {qty: '1 tsp', name: 'brown sugar'},
            {qty: '1/2 cup', name: 'tomato sauce'},
            {qty: '2 tbsp', name: 'balsamic vinegar'},
            {qty: '4 cups', name: 'beef broth'},
            {qty: '2 tbsp', name: 'parsley', prep: 'chopped, for garnish'},
        ],
        instructions: [
            `Heat a large deep skillet or Dutch oven over high heat then add the olive oil.`,
            `When the oil is hot add the stewing beef. Season with salt and pepper and sear the beef until it starts to brown. The beef will release liquid so continue searing on high heat, and the liquid will evaporate. Alternatively you could drain all the liquid.`,
            `Add the onions and garlic to the skillet and cook for about 5 minutes until the onions soften and become translucent. Turn the heat down to medium-high.`,
            `Add the paprika, caraway seeds, oregano, bay leaves and brown sugar to the skillet. Stir everything together and cook for 30 seconds. `,
            `Add the tomato sauce, balsamic vinegar, beef broth and stir. Bring to a boil, then cover and cook on low for about 2 hours or until the beef is fork tender, stirring occasionally. The liquid will reduce down a lot as the beef cooks, so feel free to add more water as needed.`,
            `Taste for seasoning and adjust with salt and pepper if needed.`,
            `Garnish with chopped parsley and serve over noodles or mashed potatoes.`,
        ],
        skillLevel: 'Medium',
        timePrep: 10,
        timeWait: null,
        timeCook: 180,
        servings: 8,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/z62yLkw.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Roast Chicken',
        description: 'Super simple and delicious chicken.',
        ingredients: [
            { qty: '1', name: '3-5 pound whole chicken'},
            { qty: '4 sprigs', name: 'rosemary', prep: 'chopped' },
            { qty: '4 sprigs', name: 'thyme', prep: 'chopped' },
            { qty: '3 tbsp', name: 'olive oil' },
            { qty: '4 cloves', name: 'garlic', prep: 'crushed' },
            { qty: '1 tsp', name: 'salt'},
            { qty: '1 tsp', name: 'pepper'},
        ],
        instructions: [
            `Use a Heavy Pan: Cast Iron Frying Pan or Dutch Oven will do just fine`,
            `Pre-Heat Oven WITH pan - at 450 degrees for 10 minutes`,
            `Rub Chicken w/ Olive Oil, rub with salt, pepper, garlic, and herbs`,
            `Put Chicken into Pan with Breast side Up - Do NOT cover!!!`,
            `Cook 45-60 minutes (160 degrees w/ Meat Thermometer) That’s it!`,
            `Better Yet: Brine with 3 Tbs of Salt & 3 Tbs Sugar in Water overnight!`,
            `Don’t forget to Rinse and Dry the Chicken after it is brined!`,
            `Then follow instructions 1-5 above`,
            `Last but not Least: Leftovers & scraps make a great chicken soup or stock!!`,
        ],
        skillLevel: '',
        timePrep: 15,
        timeWait: null,
        timeCook: 50,
        servings: 6,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Linguine with White Clam Sauce',
        description: `Nothing beats fresh clam sauce, unless you're hungry and have only your pantry to work with.`,
        ingredients: [
            { qty: '', name: '', prep: '' },
            {qty: '1', name: 'pound linguini'},
            {qty: '1 tsp', name: 'salt'},
            {qty: '1/4 cup', name: 'extra-virgin olive oil'},
            {qty: '6 fillets', name: 'flat anchovies'},
            {qty: '4 cloves', name: 'garlic', prep: 'chopped'},
            {qty: '1 teaspoon', name: 'dried thyme leaves'},
            {qty: '1/2 tsp', name: 'crushed red pepper flakes'},
            {qty: '1/2 cup', name: 'dry white wine'},
            {qty: '1 (15-ounce) can', name: 'whole baby clams with their juice'},
            {qty: '1 Handful', name: 'flat-leaf parsley', prep: 'chopped'},
        ],
        instructions: [
            `Bring a large pot of water to a boil.`,
            `Add salt and the linguini and cook to an extra chewy al dente, 9 minutes or so. The linguini will continue to cook in sauce, later.`,
            `To a large skillet heated over medium heat, add oil, anchovies, garlic, thyme and red pepper flakes.`,
            `Cook together until anchovies melt into oil and break up completely.`,
            `Add wine to the pan and give the pan a shake.`,
            `Add clams and their juice.`,
            `Drain pasta and add it to the clam sauce.`,
            `Toss and coat the pasta in sauce with clams until the pasta absorbs the flavor and juices, 2 to 3 minutes.`,
            `Remove from heat and season with salt, add parsley and serve.`
        ],
        skillLevel: 'Easy',
        timePrep: 10,
        timeWait: null,
        timeCook: 25,
        servings: 4,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/FAaEXM2.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Blueberry Buttermilk Pancakes',
        description: 'Perfect ',
        ingredients: [
            {qty: '2 cups', name: 'all-purpose flour'},
            {qty: '1/4 cup', name: 'sugar'},
            {qty: '2 1/4 teaspoons', name: 'baking powder'},
            {qty: '1/2 teaspoon', name: 'baking soda'},
            {qty: '1/2 teaspoon', name: 'salt'},
            {qty: '4', name: 'eggs'},
            {qty: '2 cups', name: 'buttermilk'},
            {qty: '1/4 cup', name: 'melted unsalted butter, plus some for frying'},
            {qty: '1 cup', name: 'blueberries', prep: 'fresh or frozen'},
        ],
        instructions: [
            `In a large bowl sift together the flour, sugar, baking powder, baking soda, and salt.`, 
            `Beat the eggs with the buttermilk and melted butter. Combine the dry and the wet ingredients into a lumpy batter, being careful not to over mix.`, 
            `Heat some butter in a skillet over medium heat. Spoon 1/3 cup of batter into the skillet and sprinkle the top with some of the blueberries. Cook for 2 to 3 minutes on each side.`, 
            `Serve with a dollop of whipped cream and maple syrup.`,
        ],
        skillLevel: 'Easy',
        timePrep: 20,
        timeWait: null,
        timeCook: 15,
        servings: 4,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/p6y2EqP.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Pan Roasted Chicken Thighs',
        description: '',
        ingredients: [
            {qty: `8`, name: `skin-on, bone-in chicken thighs`},
            {qty: ``, name: `Kosher salt and freshly ground black pepper`},
            {qty: `1 tablespoon`, name: `vegetable oil`},
        ],
        instructions: [
            `Preheat oven to 475°F.`,
            `Season chicken with salt and pepper.`,
            `Heat oil in a 12" cast-iron or heavy nonstick skillet over high heat until hot but not smoking.`,
            `Nestle chicken in skillet, skin side down, and cook 2 minutes`,
            `Reduce heat to medium-high; continue cooking skin side down, occasionally rearranging chicken thighs and rotating pan to evenly distribute heat, until fat renders and skin is golden brown, about 12 minutes`,
            `Transfer skillet to oven and cook 13 more minutes.`,
            `Flip chicken; continue cooking until skin crisps and meat is cooked through, about 5 minutes longer.`,
            `Transfer to a plate; let rest 5 minutes before serving.`,
        ],
        skillLevel: 'Easy',
        timePrep: 5,
        timeWait: null,
        timeCook: 30,
        servings: 4,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/XIO3SWb.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Wild Rice Salad',
        description: 'Hearty and filling',
        ingredients: [
            { qty: `2 cups`, name: `water`},
            { qty: `1/2 teaspoon`, name: `salt`},
            { qty: `1 cup`, name: `wild rice`},
            { qty: `1 (6-ounce) jar`, name: `marinated artichoke hearts`, prep: `drained and halved, reserve marinade`},
            { qty: `1 (6-ounce) can`, name: `green peas`},
            { qty: `1/3 cup`, name: `green bell pepper`, prep: `coarsly chopped`},
            { qty: `3`, name: `green onions`, prep: `chopped, white and green parts`},
            { qty: `1 cup`, name: `cherry or grape tomatoes`, prep: `halved`},
            { qty: `1/2 cups`, name: `olive oil`},
            { qty: `1/2 cup`, name: `white vinegar`},
            { qty: `1/4 cup`, name: `Parmesan`, prep: `grated`},
            { qty: `1 tsp`, name: `sugar`},
            { qty: `1 tsp`, name: `salt`},
            { qty: `1/4 tsp`, name: `paprika`},
            { qty: `1 clove`, name: `garlic`, prep: `minced`},
        ],
        instructions: [
            `In a 1-quart pot with a lid, bring 2 cups water and the salt to a boil. Add the rice and stir well. Reduce the heat to low, cover, and simmer for 45 minutes to 1 hour. Drain excess liquid from the rice.`,
            `Meanwhile, combine all the dressing ingredients in a jar with a tight-fitting lid and shake well. Refrigerate until ready to use.`,
            `In a large bowl, combine the rice, artichoke hearts, peas, green pepper, green onions, tomatoes, reserved marinade, and half of the dressing. Toss well. Cover and chill or eat at room temperature. Just before serving, toss again and taste. Add some of the remaining dressing, if desired. Sprinkle with the almonds and serve.`
        ],
        skillLevel: 'Easy',
        timePrep: 15,
        timeWait: null,
        timeCook: 45,
        servings: 8,
        categories: [
            'salad', 'lunch', 'side'
        ],
        heroImageUrl: '',
        imageUrl: 'https://i.imgur.com/sKCSnsg.png',
        rating: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
]

