exports.recipes = [
    {
        name: 'Instant Pot Plov (Rice Pilaf)',
        description: 'Making beef plov in an instant pot is so quick and easy and using brown rice is genius. This Instant Pot Rice recipe is a healthier, juicier and flavor packed version of beef plov.',
        ingredients: [
            { qty: '2 1/2 cups', name: 'short grain brown rice', prep: 'rinsed and drained' },
            { qty: '1 lb', name: 'beef chuck or beef stew meat', prep: 'cut into 3/4″ pieces' },
            { qty: '4 Tbsp', name: 'olive oil' },
            { qty: '4 Tbsp', name: 'butter' },
            { qty: '1', name: 'large onion', prep: 'diced' },
            { qty: '3', name: 'large carrots', prep: 'thickly julienned' },
            { qty: '3 cups', name: 'very warm water' },
            { qty: '1 Tbsp', name: 'salt' },
            { qty: '1/2 tsp', name: 'black pepper' },
            { qty: '1/2 tsp', name: 'ground cumin' },
            { qty: '1/2 tsp', name: 'ground paprika' },
            { qty: '1/2 tsp', name: 'ground coriander' },
            { qty: '1', name: 'whole head garlic', prep: 'unpeeled, cut in half crosswise' },
            { qty: '1 Tbsp', name: 'freshly chopped parsley to garnish – optional' },
        ],
        instructions: [
            `Rinse and drain rice and set aside. Set Instant pot to sauté on high heat (push sauté twice to switch to high heat) and add 4 Tbsp olive oil. Once oil is hot (but not smoking), add beef in a single layer and sauté until lightly browned (5 min), stirring occasionally.`,
            `Add 4 Tbsp butter and chopped onion and stir 3 minutes until softened.`,
            `Add julienned carrots along with all seasonings (1 Tbsp salt, 1/2 tsp pepper, 1/2 tsp cumin, 1/2 tsp paprika, 1/2 tsp coriander) and sauté 5 minutes until softened, stirring occasionally.`,
            `pread rice evenly over the top (do not stir). Push garlic halves cut-side-down, halfway into the rice. Pour very warm (or hot) water directly over the garlic cloves so you don't disturb the rice. Use the back of a wooden spoon to poke 5-7 holes through the rice to the bottom of the pot (this helps disburse flavor).`,
            `Cover and cook on high pressure 30 min (I used the "Multigrain" setting). Let instant pot rest and naturally depressurize 10 min before switching to the venting position to release steam. Make sure the steam is fully released and the pressure valve has floated down before opening the pot.`,
            `Remove garlic and set aside. Stir rice well to combine ingredients. We squeeze the garlic cloves back into the pot because they are melt-in-your mouth delicious.`
        ],
        skillLevel: 'Easy',
        timePrep: 20,
        timeWait: null,
        timeCook: 30,
        servings: 8,
        categories: [
            'dinner',
            'main',
            'side',
            'lunch',
            'beef',
            'lamb',
            'meat',
            'entree',
            'rice',
        ],
        heroImageUrl: '',
        imageUrl: 'https://natashaskitchen.com/wp-content/uploads/2018/01/Instant-Pot-Rice-Plov-3.jpg',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Borscht',
        description: '',
        ingredients: [
            { qty: '', name: '', prep: '' },
        ],
        instructions: [
            ``,
        ],
        skillLevel: '',
        timePrep: ,
        timeWait: null,
        timeCook: ,
        servings: ,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Hungarian Goulash',
        description: '',
        ingredients: [
            {qty: '4 tbsp', name: 'olive oil'},
            {qty: '2 1/2 lbs', name: 'lean stewing beef', prep: 'cut into 1 inch pieces'},
            {qty: '1 tsp', name: 'salt or to taste'},
            {qty: '1 tsp', name: 'pepper or to taste'},
            {qty: '2', name: 'large onions', prep: 'roughly chopped'},
            {qty: '5 cloves', name: 'garlic', prep: 'minced'},
            {qty: '3 tbsp', name: 'sweet paprika'},
            {qty: '1 tsp', name: 'caraway seeds', prep: 'ground'},
            {qty: '1 tsp', name: 'dried oregano'},
            {qty: '3', name: 'bay leaves'},
            {qty: '1 tsp', name: 'brown sugar'},
            {qty: '1/2 cup', name: 'tomato sauce'},
            {qty: '2 tbsp', name: 'balsamic vinegar'},
            {qty: '4 cups', name: 'beef broth'},
            {qty: '2 tbsp', name: 'parsley', prep: 'chopped, for garnish'},
        ],
        instructions: [
            `Heat a large deep skillet or Dutch oven over high heat then add the olive oil.`,
            `When the oil is hot add the stewing beef. Season with salt and pepper and sear the beef until it starts to brown. The beef will release liquid so continue searing on high heat, and the liquid will evaporate. Alternatively you could drain all the liquid.`,
            `Add the onions and garlic to the skillet and cook for about 5 minutes until the onions soften and become translucent. Turn the heat down to medium-high.`,
            `Add the paprika, caraway seeds, oregano, bay leaves and brown sugar to the skillet. Stir everything together and cook for 30 seconds. `,
            `Add the tomato sauce, balsamic vinegar, beef broth and stir. Bring to a boil, then cover and cook on low for about 2 hours or until the beef is fork tender, stirring occasionally. The liquid will reduce down a lot as the beef cooks, so feel free to add more water as needed.`,
            `Taste for seasoning and adjust with salt and pepper if needed.`,
            `Garnish with chopped parsley and serve over noodles or mashed potatoes.`,
        ],
        skillLevel: 'Medium',
        timePrep: 10,
        timeWait: null,
        timeCook: 180,
        servings: 8,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Roast Chicken',
        description: '',
        ingredients: [
            { qty: '', name: '', prep: '' },
        ],
        instructions: [
            ``,
        ],
        skillLevel: '',
        timePrep: ,
        timeWait: null,
        timeCook: ,
        servings: ,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Linguine with White Clam Sauce',
        description: '',
        ingredients: [
            { qty: '', name: '', prep: '' },
        ],
        instructions: [
            ``,
        ],
        skillLevel: '',
        timePrep: ,
        timeWait: null,
        timeCook: ,
        servings: ,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Pancakes',
        description: '',
        ingredients: [
            {qty: '2 cups', name: 'all-purpose flour'},
            {qty: '1/4 cup', name: 'sugar'},
            {qty: '2 1/4 teaspoons', name: 'baking powder'},
            {qty: '1/2 teaspoon', name: 'baking soda'},
            {qty: '1/2 teaspoon', name: 'salt'},
            {qty: '4', name: 'eggs'},
            {qty: '2 cups', name: 'buttermilk'},
            {qty: '1/4 cup', name: 'melted unsalted butter, plus some for frying'},
            {qty: '1 cup', name: 'blueberries', prep: 'fresh or frozen'},
        ],
        instructions: [
            `In a large bowl sift together the flour, sugar, baking powder, baking soda, and salt.`, 
            `Beat the eggs with the buttermilk and melted butter. Combine the dry and the wet ingredients into a lumpy batter, being careful not to over mix.`, 
            `Heat some butter in a skillet over medium heat. Spoon 1/3 cup of batter into the skillet and sprinkle the top with some of the blueberries. Cook for 2 to 3 minutes on each side.`, 
            `Serve with a dollop of whipped cream and maple syrup.`,
        ],
        skillLevel: 'Easy',
        timePrep: 20,
        timeWait: null,
        timeCook: 15,
        servings: 4,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
    {
        name: 'Pan Roasted Chicken Thighs',
        description: '',
        ingredients: [
            {qty: `8`, name: `skin-on, bone-in chicken thighs`},
            {qty: ``, name: `Kosher salt and freshly ground black pepper`},
            {qty: `1 tablespoon`, name: `vegetable oil`},
        ],
        instructions: [
            `Preheat oven to 475°F.`,
            `Season chicken with salt and pepper.`,
            `Heat oil in a 12" cast-iron or heavy nonstick skillet over high heat until hot but not smoking.`,
            `Nestle chicken in skillet, skin side down, and cook 2 minutes`,
            `Reduce heat to medium-high; continue cooking skin side down, occasionally rearranging chicken thighs and rotating pan to evenly distribute heat, until fat renders and skin is golden brown, about 12 minutes`,
            `Transfer skillet to oven and cook 13 more minutes.`,
            `Flip chicken; continue cooking until skin crisps and meat is cooked through, about 5 minutes longer.`,
            `Transfer to a plate; let rest 5 minutes before serving.`,
        ],
        skillLevel: 'Easy',
        timePrep: 5,
        timeWait: null,
        timeCook: 30,
        servings: 4,
        categories: [
            '',
        ],
        heroImageUrl: '',
        imageUrl: '',
        stars: null,
        addedBy: 'Mike Feldberg',
        userId: '5ce73f716464302cd903f328',
        deletedAt: null,
    },
]